name: foap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  google_mobile_ads: ^3.0.0
  flutter_login_facebook: ^1.8.0
  sign_in_with_apple: ^5.0.0
  flutter_phoenix: ^1.1.1
  image_picker: ^1.0.1
  in_app_purchase: ^3.1.7
  shared_preferences: ^2.2.0
  webview_flutter: ^4.2.2
  local_auth: ^2.1.6
  pin_code_text_field: ^1.8.0
  currency_picker: ^2.0.16
  country_picker: ^2.0.20
  adaptive_action_sheet: ^2.0.2
  video_player: ^2.7.0
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  get: ^4.6.5
  dots_indicator: ^3.0.0
  flutter_easyloading: ^3.0.5
  story_view: ^0.15.0
  keyboard_attachable: ^2.1.0
  detectable_text_field: ^2.1.0
  firebase_crashlytics: ^3.3.4
  chewie: ^1.7.0
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  flutter_linkify: ^6.0.0
  flutter_sound: ^9.2.13
  get_it: ^7.6.0
  just_audio: ^0.9.34
  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  agora_rtc_engine: ^6.2.1
  permission_handler: ^10.4.3
  flutter_ringtone_player: ^3.2.0
  socket_io_client: ^2.0.2
  focused_menu: ^1.0.5
  flutter_fgbg: ^0.3.0
  pip_view: ^0.9.7
  google_sign_in: ^6.1.4
  flutter_callkit_incoming: ^2.0.0+1
  uuid: ^3.0.7
  mime_type: ^1.0.0
  photo_manager: ^2.6.0
  share_plus: ^7.0.2
  google_mlkit_smart_reply: ^0.8.0
  google_mlkit_commons: ^0.5.0
  flutter_archive: ^5.0.0
  push: ^1.0.0
  overlay_support: ^2.1.0
  flutter_local_notifications: ^16.0.0-dev.1
  camera: ^0.10.5+2
  profanity_filter: ^2.0.0
  flutter_contacts: ^1.1.7
  fl_location: ^2.0.0+1
  google_static_maps_controller: ^1.0.0
  progress_state_button: ^1.0.4
  map_launcher: ^2.5.0+1
  flutter_switch: ^0.3.2
  flutter_drawing_board: ^0.4.4+2
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.0.4
  avatar_glow: ^2.0.2
  facebook_audience_network: ^1.0.1
  pull_to_refresh: ^2.0.0
  flare_flutter: ^3.0.2
  ripple_wave: ^0.1.3
  animated_text_kit: ^4.2.2
  pinch_zoom: ^1.0.0
  oktoast: ^3.3.1
  android_path_provider: ^0.3.0
  percent_indicator: ^4.2.3
  auto_orientation: ^2.3.1
  flutter_keyboard_visibility: ^5.4.1
  animate_do: ^3.0.2
#  flutter_braintree: ^3.0.0
#  razorpay_flutter: ^1.3.5
#  flutter_stripe: ^9.3.0
  sqflite: ^2.2.8+4
  readmore: ^2.2.0
  qr_flutter: ^4.1.0
  widgets_to_image: ^0.0.2
#  device_info_plus: ^9.0.2
  encrypt: ^5.0.1
  video_compress_ds: ^3.1.6
  aescryptojs: ^1.0.0
  ffmpeg_kit_flutter: ^5.1.0
  flutter_polls: ^0.1.2
  geocoding: ^2.1.0
  latlng: ^1.0.0
  open_filex: ^4.3.2
  flutter_rating_bar: ^4.0.1
  extended_image: ^8.1.0
  visibility_detector: ^0.3.3
  lottie: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.0
  google_maps_flutter: ^2.3.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  background_downloader: ^7.6.0
  file_picker: ^5.3.2
  syncfusion_flutter_sliders: ^22.1.39
  any_link_preview: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  record: ^4.4.4
  flutter_video_info: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ">=1.0.4"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/resources/
    - assets/
    - assets/chatbg/
    - assets/lottie/
    - assets/images/
    - assets/tv/
    - assets/svg/
    - assets/svg/bold/
    - assets/svg/outline/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
